# Generated by Django 3.1.3 on 2021-02-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210206_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
