# Generated by Django 3.1.3 on 2021-02-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20210206_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourhour',
            name='hours',
        ),
    ]
