# Generated by Django 3.1.3 on 2021-02-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_remove_labourhour_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourhour',
            name='overtime_hours',
        ),
    ]
