# Generated by Django 3.1.3 on 2021-02-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_remove_labourhour_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Temporary', 'temp'), ('Permanent', 'perm'), ('Managerial', 'mng')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.worksite', verbose_name='Worksite'),
        ),
    ]
